apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
  name: snowdrop-site-angular
spec:
  rules:
    - host: snowdrop.me
      http:
        paths:
          - backend:
              serviceName: snowdrop-site-angular
              servicePort: 80
            path: /
    - host: snowdrop.dev
      http:
        paths:
          - backend:
              serviceName: snowdrop-site-angular
              servicePort: 80
            path: /
  tls:
    - hosts:
        - snowdrop.me
      secretName: www-snowdrop-me-tls
    - hosts:
        - snowdrop.dev
      secretName: www-snowdrop-dev-tls